// PreScout visual system: paper surfaces, ink text, one safety-orange accent.
export const Colors = {
  background: '#FAFAF7',
  surface: '#FFFFFF',
  surfaceMuted: '#F1F2F0',
  ink: '#151A1E',
  inkMuted: '#5C6670',
  border: '#E4E7EA',
  accent: '#E8590C',
  accentContainer: '#FFF0E6',
  success: '#2F9E44',
  successContainer: '#E6F6E9',
  warning: '#E67700',
  warningContainer: '#FFF3E0',
  danger: '#C92A2A',
  dangerContainer: '#FCE9E9',
  info: '#0B7285',
  infoContainer: '#E3F4F7',
  white: '#FFFFFF',
  black: '#000000',

  // Legacy aliases — removed in Task 13 once no screen references them.
  surfaceDim: '#F1F2F0',
  surfaceBright: '#FFFFFF',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#FAFAF7',
  surfaceContainer: '#FFFFFF',
  surfaceContainerHigh: '#F1F2F0',
  surfaceContainerHighest: '#E4E7EA',
  surfaceVariant: '#E4E7EA',
  primary: '#151A1E',
  primaryFixed: '#151A1E',
  primaryFixedDim: '#5C6670',
  primaryContainer: '#F1F2F0',
  onPrimary: '#FFFFFF',
  onSurface: '#151A1E',
  onSurfaceVariant: '#5C6670',
  onBackground: '#151A1E',
  outline: '#5C6670',
  outlineVariant: '#E4E7EA',
  tertiary: '#E8590C',
  tertiaryFixed: '#E8590C',
  tertiaryFixedDim: '#C94D0A',
  tertiaryContainer: '#FFF0E6',
  onTertiary: '#FFFFFF',
  onTertiaryContainer: '#7A2E05',
  error: '#C92A2A',
  errorContainer: '#FCE9E9',
  onError: '#FFFFFF',
  onErrorContainer: '#7A1C1C',
  secondaryContainer: '#FCE9E9',
  secondary: '#C92A2A',
  onWarning: '#FFFFFF',
  onWarningContainer: '#7A3F00',
  accentBlue: '#0B7285',
  accentBlueHover: '#095C6B',
  accentBlueLight: '#E3F4F7',
};

export const Spacing = { unit: 4, sm: 8, md: 12, lg: 16, xl: 20, xxl: 24, container: 20, marginMobile: 18, marginDesktop: 32 };
